name: "Terrafrom CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_LOG: INFO
  TF_INPUT: False


jobs:  
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Format"
        run: terraform fmt --check --diff

      - name: "Terraform Validate"
        if: (success() || failure())
        run: terraform validate
