name: "terraform_plan"

on:
  workflow_run:
    workflows: ["terraform_check"]
    types:
      - completed

jobs:
  terraform_gate:
    name: "terraform_gate"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Apply"
        run: terraform plan